version: '3.8'

services:
  # --- PostgreSQL ---
  postgres:
    image: postgres:16
    container_name: storage-postgres
    environment:
      POSTGRES_USER: lev
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    networks:
      - app-network

  # --- Бэкенд ---
  backend:
    build: ./storage-backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: lev
      DB_PASSWORD: 123
      DB_NAME: postgres
    depends_on:
      - postgres
    networks:
      - app-network

  # --- Фронтенд ---
  frontend:
    build: ./storage-project
    env_file:
    - ./storage-project/.env
    ports:
      - "80:80"
    environment:
      VUE_APP_API_URL: "http://backend:8080/api/v1/inventory"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
